# Setup
title: Guri's IBM i Page on GitHub
description: # >- # this means to ignore newlines until "baseurl:"
  <font color="#ff66e3">Copyright 2023 "Guri The Cat".
  This project is licensed under the MIT License.</font>
url: "https://guricat.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/GuriPages" # the subpath of your site, e.g. /blog
avatar: /ぐりさん2.png
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter_username: GuriCatNyan
github_username:  GuriCat
logo: favicon.ico

lang: ja

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Guri
  url: 
  email: 
